/**
 * Shared Roles across Frontend and Backend
 */
export enum Role {
  ADMIN = 'ADMIN',
  KITCHEN = 'KITCHEN',
  DISPATCH = 'DISPATCH',
  DRIVER = 'DRIVER',
}

export enum Permission {
  STAFF_MANAGE = 'STAFF_MANAGE',
  CATALOGUE_MANAGE = 'CATALOGUE_MANAGE',
  COMPANY_MANAGE = 'COMPANY_MANAGE',
  EMPLOYEE_MANAGE = 'EMPLOYEE_MANAGE',

  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_VIEW = 'ORDER_VIEW',
  ORDER_OVERRIDE = 'ORDER_OVERRIDE',

  KITCHEN_VIEW = 'KITCHEN_VIEW',
  KITCHEN_UPDATE = 'KITCHEN_UPDATE',

  DISPATCH_VIEW = 'DISPATCH_VIEW',
  DISPATCH_UPDATE = 'DISPATCH_UPDATE',

  DRIVER_VIEW_OWN = 'DRIVER_VIEW_OWN',
  DRIVER_DELIVER = 'DRIVER_DELIVER',

  BILLING_MANAGE = 'BILLING_MANAGE',
  SETTINGS_MANAGE = 'SETTINGS_MANAGE',
}
