ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'KITCHEN_IN_PROGRESS';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'KITCHEN_READY';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'DISPATCH_READY';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'OUT_FOR_DELIVERY';
